### ISSUE TITLE
rubocop и стили

### ISSUE THREAD

**Issue by XaoGao** [o-200/animated-garbanzo#1]
Желательно добавить гем rubocop https://github.com/rubocop/rubocop и конфигурационный файл для него в корень проекта, так как в проекте "плывет" стиль, иногда используются двойные ковычки, а иногда одинарные
(https://github.com/o-200/codewars-exporter/blob/822f849cd493c55f8920bcb0e6ab99ca17735443/lib/parser/parser.rb#L1
(https://github.com/o-200/codewars-exporter/blob/822f849cd493c55f8920bcb0e6ab99ca17735443/lib/parser/parser.rb#L2) ненужный return https://github.com/o-200/codewars-exporter/blob/822f849cd493c55f8920bcb0e6ab99ca17735443/lib/parser/parser.rb#L88
В руби есть правило наименование объекта, есть класс https://github.com/o-200/codewars-exporter/blob/main/lib/api/table.rb он должен называться не ApiTable а нужно было создать модуль Api и в нем класс Table, класс Profile тоже должен быть в модуле Api.
(https://github.com/o-200/codewars-exporter/blob/822f849cd493c55f8920bcb0e6ab99ca17735443/lib/api/profile.rb#L40) не только парсит json, но и делает json запрос, так что лучше переименовать.
Почему https://github.com/o-200/codewars-exporter/blob/822f849cd493c55f8920bcb0e6ab99ca17735443/lib/parser/parser.rb#L77 @browser не объявить в конструкторе ?
Так же принято что в программе в директории lib будет лежать файл с наименованием программы, который будет содержать в себе все require.
https://github.com/o-200/codewars-exporter/blob/822f849cd493c55f8920bcb0e6ab99ca17735443/lib/parser/parser.rb#L101 
https://github.com/o-200/codewars-exporter/blob/822f849cd493c55f8920bcb0e6ab99ca17735443/lib/parser/parser.rb#L118
тут нет смысла возвращать self
```ruby
def scroll_to_bottom_page(browser)
    loop do
      link_number = browser.links.size
      browser.scroll.to :bottom
      sleep(2)

      break if browser.links.size == link_number
    end

    browser
  end
```
лучше
```
def scroll_to_bottom_page(browser)
    loop do
      link_number = browser.links.size
      browser.scroll.to :bottom
      sleep(2)

      return browser if browser.links.size == link_number
    end
  end
```
Тут https://github.com/o-200/codewars-exporter/blob/822f849cd493c55f8920bcb0e6ab99ca17735443/lib/parser/parser.rb#L107 лучше просто использовать функцию map

**Comment by o-200** [comment]
> тут нет смысла возвращать self

для использования методов как chaining methods нужно в конце возращать `self`

`parse.separate_data.place_by_files`

**Comment by o-200** [comment]
> @browser не объявить в конструкторе ?

Если поместить создание @browser в конструктор, то при использовании скрипта окно браузера просто будет мешать пользователю и отвлекать. Оно не задействуется в самом начале жизненного цикла класса.
